export const products = [
	{
		id: "1",
		imagePath: "/about.jpg",
		manufacturer: "MWM",
		name: "Motor MWM",
		price: 15000,
		description: [
			"Motor: 2506A – E15TAG4",
			"Arranjo: MGEF – 5003",
			"Potência: 624 KV A",
			"Peso Seco: 1,633 kg",
			"Sistema de Combustível: Injeção Direta (Eletrônico)",
		],
	},
	{
		id: "2",
		imagePath: "/about.jpg",
		manufacturer: "Yanmar",
		name: "Motor Yanmar",
		price: 30000,
		description: [
			"Motor: 2506A – E15TAG4",
			"Arranjo: MGEF – 5003",
			"Potência: 624 KV A",
			"Peso Seco: 1,633 kg",
			"Sistema de Combustível: Injeção Direta (Eletrônico)",
		],
	},
	{
		id: "3",
		imagePath: "/about.jpg",
		manufacturer: "Caterpillar",
		name: "Motor Long Block Cat Modelo C4.4 – NOVO",
		price: 300000,
		description: [
			"Motor: 2506A – E15TAG4",
			"Arranjo: MGEF – 5003",
			"Potência: 624 KV A",
			"Peso Seco: 1,633 kg",
			"Sistema de Combustível: Injeção Direta (Eletrônico)",
		],
	},
	{
		id: "4",
		imagePath: "/about.jpg",
		manufacturer: "Yanmar",
		name: "Motor Yanmar 2",
		price: 25000,
		description: [
			"Motor: 2506A – E15TAG4",
			"Arranjo: MGEF – 5003",
			"Potência: 624 KV A",
			"Peso Seco: 1,633 kg",
			"Sistema de Combustível: Injeção Direta (Eletrônico)",
		],
	},
	{
		id: "5",
		imagePath: "/about.jpg",
		manufacturer: "MWM",
		name: "Motor MWM 2",
		price: 150000,
		description: [
			"Motor: 2506A – E15TAG4",
			"Arranjo: MGEF – 5003",
			"Potência: 624 KV A",
			"Peso Seco: 1,633 kg",
			"Sistema de Combustível: Injeção Direta (Eletrônico)",
		],
	},
];
